#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".tsx\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

for FILE in $STAGED_FILES
do
  npx eslint "$FILE"

  if [[ "$?" == 0 ]]; then
    echo "ESLint Passed: $FILE"
  else
    echo "ESLint Failed: $FILE"
    PASS=false
  fi
done

if ! $PASS; then
  echo "Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  echo "ESLint succeeded"
fi

for FILE in $STAGED_FILES
do
  npx prettier --check "$FILE"

  if [[ "$?" == 0 ]]; then
    echo "ESLint Passed: $FILE"
  else
    echo "ESLint Failed: $FILE"
    PASS=false
  fi
done

echo "Prettier done for all files!"

if ! $PASS; then
  echo "Your commit contains files that should pass prettier but do not. Please fix the Prettier issues and try again.\n"
  exit 1
else
  echo "Prettier succeeded"
fi

exit $?